# Generated by Django 2.2.7 on 2019-11-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20191115_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
