# Generated by Django 2.2.7 on 2019-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='location',
            field=models.TextField(default='Vadodara'),
            preserve_default=False,
        ),
    ]
