# Generated by Django 2.2.7 on 2019-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('mess_staff', 'Mess Staff')], default='student', max_length=15),
        ),
    ]
