# Generated by Django 2.2.7 on 2019-11-12 05:57

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', accounts.managers.ProfileManager()),
            ],
        ),
    ]
