# Generated by Django 2.2.7 on 2019-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_link', models.TextField()),
                ('holiday_link', models.TextField()),
                ('academic_link', models.TextField()),
            ],
        ),
    ]
